```{r}
source("setup.R")
source("util.R")
source("prepare_data.R")
source("model_pipeline.R")
source("plot.R")
```

```{r}
# Set random seed for reproducibility
set.seed(81)
n <- 1000000  # Number of observations

# give most mass to reference levels X1="A" and X2="1"
p_X1 <- c(A = 0.4, B = 0.3, C = 0.3)
p_X2 <- c(`1` = 0.4, `11` = 0.2, `3` = 0.2, `4` = 0.2)

# Generate features
tbl <- data.frame(
  X1 = factor(sample(names(p_X1), n, replace = TRUE, prob = p_X1), levels = names(p_X1)),
  X2 = factor(sample(names(p_X2), n, replace = TRUE, prob = p_X2), levels = names(p_X2)),
  O1 = factor(sample(c("OA","OB","OC"), n, replace = TRUE)),
  O2 = factor(sample(c("O1","O11","O3","O4"), n, replace = TRUE))
)

# External model parameters
beta0_ext <- 1.5
beta1_ext <- c(OA = 0, OB = 0.5, OC = 1)
beta2_ext <- c(`O1` = 0, `O11` = 0.3, `O3` = 0.6, `O4` = 0.9)

# Compute offset (link scale)
X_ext <- model.matrix(~ O1 + O2, data = tbl)
beta_ext <- c(beta0_ext, beta1_ext[c("OB", "OC")], beta2_ext[c("O11", "O3", "O4")])
tbl$offset <- as.vector(X_ext %*% beta_ext)

# Define weights
tbl$weights <- runif(n, 0, 1)

# True model parameters
beta0 <- 0.2
beta1 <- c(A = 0, B = 0.1, C = -0.1)
beta2 <- c(`1` = 0, `11` = 0.05, `3` = 0.1, `4` = 0.15)
# Interaction: only X1 B at X2 level 2, 3, 4
int_B2 <- 0.1  # X1=B & X2=11
int_B3 <- 0.2   # X1=B & X2=3
int_B4 <- 0.3   # X1=B & X2=4

# Full design matrix with interactions
X_full <- model.matrix(~ X1 * X2, data = tbl)
# Construct coefficient vector in the order of X_full columns
# Align coefficients with all columns of X_full
beta_vec <- setNames(rep(0, ncol(X_full)), colnames(X_full))

# Fill known coefficients
beta_vec["(Intercept)"] <- beta0
beta_vec["X1B"] <- beta1["B"]
beta_vec["X1C"] <- beta1["C"]

beta_vec["X211"] <- beta2["11"]
beta_vec["X23"] <- beta2["3"]
beta_vec["X24"] <- beta2["4"]

# Interaction only for X1B 
beta_vec["X1B:X211"] <- int_B2
beta_vec["X1B:X23"] <- int_B3
beta_vec["X1B:X24"] <- int_B4

# Linear predictor and simulation
log_mu <- tbl$offset + 
          X_full %*% beta_vec
mu <- exp(log_mu)

library(tweedie)
Y <- rtweedie(n, mu = as.vector(mu), power = 1.8, phi = 5)
tbl$obs <- Y * tbl$weights

data <- tbl[c("obs", "X1", "X2", "offset", "weights")]
data$offset <- exp(tbl$offset) # offset on response scale
```

```{r}
distribution <- "tweedie"
tweedie_power <- 1.8

target <- "obs"
weights <- "weights"
offset <- "offset"
features <- c("X1", "X2")
features_i <- c("X1:X2")

sparse_matrix <- TRUE
test_size <- 0.2
```

```{r}
model_n <- run_model_pipeline(data, distribution, features, interactions = features_i ,target_col=target, weight_col=weights, offset_col=offset, sparse_matrix=sparse_matrix, test_size = test_size, tweedie_power = tweedie_power)
```

```{r}
plot_deviance_train_test(model_n$deviance_train, model_n$deviance_test)
```

```{r}
plot_deviance_train_test(model_n$deviance_train, model_n$deviance_test,T)
```

```{r}
print(summarize_risk_factor_levels_per_s(model_n))
```

```{r}
plot_risk_factors_all(model_n,data,30,exposure_col = "weights")
```

```{r}
plots_risk_factors_slider <- plot_all_features_slider(
  pipeline_output = model_n,
  exposure_df = data,
  features = c("X1", "X2", "X1:X2"),
  exposure_col = weights
)
plots_risk_factors_slider
```

```{r}
#Saves an HTML file with one plot per each feature, where the regularization parameter can be individually set for each feature
save_all_plots_grid(
  all_plots = plots_risk_factors_slider, 
  output_file = "risk_analysis_dashboard1.html",
  title = "Risk Factor Analysis", 
  plots_per_row = 2
)
```

```{r}
#Saves an HTML file with one plots for each feature, allowing the same regularization parameter to be set for all plots via a single slider
create_risk_factor_dashboard(
  pipeline_output = model_n,
  exposure_df = data,
  features = c("X1", "X2", "X1:X2"),
  exposure_col = weights,
  output_file = "risk_analysis_dashboard2.html",
  title = "Risk Analysis Dashboard"
)
```

```{r}
plots_features_actual_vs_predicted_slider_test <- plot_all_features_actual_vs_predicted(
  pipeline_output = model_n,
  data = data,
  features = c("X1", "X2", "X1:X2"),
  target_col = "obs",
  weight_col = "weights",
  train_or_test = "test" #"train"
)
plots_features_actual_vs_predicted_slider_test

```

```{r}
model_n_r <- run_model_pipeline_relax(model_n, data, features, features_i, distribution,
                           target_col = target, weight_col = weights, offset_col = offset, sparse_matrix=TRUE)
```

```{r}
plot_risk_factors_compare_model(model_n,model_n_r,data,exposure_col = "weights", lambda_index = 30)
```

```{r}
plot_all_feature_predictions_comparison(model_n, model_n_r, data, "obs", "weights", lambda_index = 30, "test" #"train"
                                        )
```

```{r}
model_n_r_p <- run_model_pipeline_relax(model_n, data, features, interactions=features_i , distribution,
                           target_col = target, weight_col = weights, offset_col = offset, sparse_matrix=TRUE, mode = "partial_fit", lambda_index=c(30))
```

```{r}
plot_risk_factors_compare_model(model_n,model_n_r_p,data,exposure_col = "weights", lambda_index = 30)
```
